# docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - "3000" # Exposes port internally to other services
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static # Serve static files if needed
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge